### ISSUE TITLE
Localization doesn't work.

### ISSUE THREAD

**Issue by AlexandrStarov** [damienbod/AspNet5Localization#1]
Hello!
I have tried your sample, but it seems it is not working.
Localization doesn't work correctly. Only work neutral resource strings.
![errorrecourses](https://cloud.githubusercontent.com/assets/14146298/10729264/d44b2396-7bf0-11e5-8545-a6514c7d0da7.png)
Appreciate any help.

**Comment by damienbod** [comment]
Hi

This is a visual studio tooling bug. The localization works if you start from the console. 

See https://github.com/aspnet/Tooling/issues/236

Or read the blog:

http://damienbod.com/2015/10/21/asp-net-5-mvc-6-localization/

Greetings Damien

**Comment by nickgru** [comment]
Hello, 

I was trying to get localization to work with RC1 but have run into issues with mine as well as your project.  It seems to not able to return the resource.  When it tries to get the resource "Name" it just returns Name because it is erroring out with the ResourceManagerStringLocalizer.   I've tried your project running in VS and Console and stil does not return the appropriate resource.  I'm not sure what I am missing here.  

When I to evaluate in in debug I get this: 
?_htmlLocalizer["Name"];
{Name}
    Name: "Name"
    ResourceNotFound: true
    Value: "Name"

Thanks for your help.

**Comment by damienbod** [comment]
rc1 update: tooling still not working
created resx class => internal and not public
