### ISSUE TITLE
Add DataAnnotationLocalizerProvider definition

### ISSUE THREAD

**Issue by damienbod** [damienbod/AspNet5Localization#19]
https://github.com/aspnet/Localization/issues/286#issuecomment-249708911
```
.AddDataAnnotationsLocalization(options => {
    options.DataAnnotationLocalizerProvider = (type, factory) => 
        factory.Create(typeof(SharedResource));
});
```

**Comment by damienbod** [comment]
not required

**Comment by tklawsuc** [comment]
I found this code to be required if you want to use `SharedResource` in annotations on view models. 

```
public class CompanyViewModel
{
  [Display(Name = "ShortName")]
  public string ShortName { get; set; }
}
```

`AddDataAnnotationsLocalization()`, Resource key is CompanyViewModel. 

`.AddDataAnnotationsLocalization(options => {
    options.DataAnnotationLocalizerProvider = (type, factory) => 
        factory.Create(typeof(SharedResource));
});`, Resource key is ShareResource

The issue I have is when I try to use both resource keys: `CompanyViewModel` by default and  `SharedResource` by setting the `ResourceType` display attribute. Regardless of how I setup`AddDataAnnotationsLocalization`, I get an error.

```
public class CompanyViewModel
{
  [Display(Name = "ShortName", ResourceType = typeof(SharedResource))]
  public string ShortName { get; set; }
}
```
Results in this error
`InvalidOperationException: Cannot retrieve property 'Name' because localization failed. Type 'MyNamespace.SharedResource' is not public or does not contain a public static string property with the name 'ShortName'`. I also tried adding `ShortName` into the `SharedResource`.
